# Generated by Django 4.0 on 2023-01-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_model3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model1',
        ),
    ]
